## Component kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Component
metadata:
  name: hello-world-php-service
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Hello World PHP Service
    core.choreo.dev/description: A simple service built with PHP.
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: default-project
    core.choreo.dev/name: hello-world-php-service
spec:
  type: Service
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
      authentication:
        secretRef: choreo-bot-git-pat
---

## DeploymentTrack kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: DeploymentTrack
metadata:
  name: hello-world-php-service-main
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Main Deployment Track
    core.choreo.dev/description: Deployment track for the Hello World PHP service.
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: default-project
    core.choreo.dev/component: hello-world-php-service
    core.choreo.dev/name: hello-world-php-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /hello-world-php-service
    buildConfiguration:
      buildpack:
        name: PHP
---

## Build kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Build
metadata:
  name: hello-world-php-service-build-01
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Default Build
    core.choreo.dev/description: Initial build configuration for the Hello World PHP service.
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: default-project
    core.choreo.dev/component: hello-world-php-service
    core.choreo.dev/deployment-track: hello-world-php-service-main
    core.choreo.dev/name: hello-world-php-service-build-01
spec:
  branch: main
  path: /hello-world-php-service
  buildConfiguration:
    buildpack:
      name: PHP
      version: 8.1.x
---

## Deployment kind (Namespaced)
apiVersion: core.choreo.dev/v1
kind: Deployment
metadata:
  name: hello-world-php-service-development-deployment-01
  namespace: default-organization
  annotations:
    core.choreo.dev/display-name: Hello World PHP Service Deployment
    core.choreo.dev/description: Initial deployment configuration for the Hello World PHP service.
  labels:
    core.choreo.dev/organization: default-organization
    core.choreo.dev/project: default-project
    core.choreo.dev/environment: development
    core.choreo.dev/component: hello-world-php-service
    core.choreo.dev/deployment-track: hello-world-php-service-main
    core.choreo.dev/name: hello-world-php-service-development-deployment-01
spec:
  deploymentArtifactRef: hello-world-php-service-build-01
