apiVersion: openchoreo.dev/v1alpha1
kind: Workflow
metadata:
  annotations:
    openchoreo.dev/component-workflow-parameters: |
      repoUrl: parameters.repository.url
      branch: parameters.repository.revision.branch
      commit: parameters.repository.revision.commit
      appPath: parameters.repository.appPath
    openchoreo.dev/workflow-scope: component
  name: docker
  namespace: default
spec:
  buildPlaneRef:
    kind: BuildPlane
    name: default
  externalRefs:
    - apiVersion: openchoreo.dev/v1alpha1
      id: git-secret-reference
      kind: SecretReference
      name: ${parameters.repository.secretRef}
  runTemplate:
    .....

  results:
    - id: image-name
      description: "The image name produced in the build-image step"
      valueFrom:
        taskResult:
          task: build-image
          result: image-name
    - name: registry-url
      description: "The full registry URL of the published image"
      valueFrom:
        expression: "ghcr.io/openchoreo/sample-workloads/greeting-service"
    - name: execution-time
      description: "The total execution time of the workflow"
      valueFrom:
        expression: ${workflow.status.completionTime - workflow.status.startTime}
    - name: workload
      description: "The generated Workload manifest for the built image"
      valueFrom:
        taskResult:
          task: generate-workload-cr
          result: workload-cr
---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
spec:
  ....
status:
  results:
    - name: image-name
      description: ""
      value: "default-greeting-service:v1"
    - name: registry-url
      description: ""
      value: "ghcr.io/openchoreo/sample-workloads/greeting-service:v1"
    - name: execution-time
      description: ""
      value: "5m30s"
    - name: workload
      description: ""
      value: |
            apiVersion: openchoreo.dev/v1alpha1
            kind: Workload
            metadata:
            name: greeting-service
            namespace: default
            spec:
            componentType:
                kind: ComponentType
                name: deployment/service
            owner:
                projectName: default
            autoDeploy: true
      
