apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
 name: intern-user-option-2
 namespace: default
 labels:
    openchoreo.dev/secret-type: git-credentials
    openchoreo.dev/workflow-plane-kind: ClusterWorkflowPlane
    openchoreo.dev/workflow-plane-name: default
spec:
 template:
   type: Opaque
 refreshInterval: 1h
 data:
   - secretKey: aws-access-key-id
     remoteRef:
       key: secret/default/git/codecommit-access-key
       property: value
   - secretKey: aws-secret-access-key
     remoteRef:
       key: secret/default/git/codecommit-secret-key
       property: value
   - secretKey: aws-role-arn
     remoteRef:
       key: secret/default/git/codecommit-role-arn
       property: value
