apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  labels:
    kubernetes.io/secret-type: basic-auth
    openchoreo.dev/secret-type: git-credentials
    openchoreo.dev/workflow-plane-kind: ClusterWorkflowPlane
    openchoreo.dev/workflow-plane-name: default
  name: intern-user-2
  namespace: default
spec:
  data:
  - remoteRef:
      key: secret/default/git/intern-user
      property: password
    secretKey: password
  - remoteRef:
      key: secret/default/git/intern-user
      property: username
    secretKey: username
  refreshInterval: 1h
  template:
    type: kubernetes.io/basic-auth
