apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: test-secret-ref
  namespace: default
spec:
  template:
    type: kubernetes.io/basic-auth
    metadata:
      labels:
        app: greeter-service
  data:
    - secretKey: password
      remoteRef:
        key: test-secret-ref
        property: password
  refreshInterval: 15m
